### PR TITLE
Feature/aqi 2866

### PR DESCRIPTION
**Pull request by AQI-DanG**
Changed enum fields to ints on Activity, removed unused enums.  Per ADR

### CODE REVIEW

**Comment by jz-aqi** [comment]
I thought we are still keeping the enum, how are the consumers know which is which?

**Comment by AQI-DanG** [comment]
> I thought we are still keeping the enum, how are the consumers going to know which is which?

The consumers decide which is which we just store the values for them.

**Comment by jz-aqi** [comment]
what happens when we want to query "in progress" activities when consumers all use different values?

**Comment by JonathanRobertson-AQI** [comment]
> what happens when we want to query "in progress" activities when consumers all use different values?

This was discussed in ADR yesterday.  This won't be strongly enforced on the back end.  Some of those details are in the epic, but we'll need to document the codes somewhere (APIM documentation perhaps).

**Review by JonathanRobertson-AQI — APPROVED** [review]
looks like what was discussed in ADR, nice job :)

**Pull request merged**
